### ISSUE TITLE
[RoR training] Advanced Ruby document

### ISSUE THREAD

**Issue by tran-hai-mulodo** [tran-hai-mulodo/training-rails6#13]
This issue is used to describe some tips or trick about:
- String, Arrays, Hashes
- Operator, Methods
- Classes, Objects, and Modules
- Databases
- Error Handling, Exception

**Comment by bien-thy-mulodo** [comment]
## Tips and Tricks
- [10 Ruby tricks to improve your code (or not)](https://devblast.com/b/ruby-tricks-improve-code)
- [5 Ruby on Rails Tips You Probably Don’t Know](https://hackernoon.com/5-ruby-on-rails-tips-you-probably-dont-know-8b80b4a0890f)
- [Rails Console Magic Tricks](https://medium.com/better-programming/rails-console-magic-tricks-da1fdd657d32?)

**Comment by nguyen-dat-mulodo** [comment]
@bien-thy-mulodo Please describe some example or copy source and paste it at comment. It's easy for reviewing.
